<<<<<<< HEAD
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Jaime Gomez-Ramirez 
email: jd.gomezramirez@gmail.com
description: > # this means to ignore newlines until "url:"
   Personal website Complexity Scientist in the era of Social Distancing.
footer_text: >

url: grjd.github.io/gomez # the base hostname & protocol for your site
baseurl: /gomez # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: grjd # your GitHub user name
twitter_username: gomezramirez_ac # your Twitter handle
linkedin_username: # your Lin_ackedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

contact_note: >
  Please drop me a line if you feel like.

google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Ars longa, vita brevis
blog_description:  Notes on the History Ideas for the Complex Uncertain Future.

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
=======
---
title: Gomez
timezone: UTC
>>>>>>> ddb166c6c893392d22e71710923df6b12f0dd0b5
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
name: Jaime Gomez-Ramirez
email: jd.gomezramirez@gmail.com
description: 'Personal website Complexity Scientist in the era of Social Distancing.

'
footer_text: ''
url: grjd.github.io
baseurl: 
last_updated: 
serve_og_meta: false
og_image: 
github_username: grjd
twitter_username: gomezramirez_ac
linkedin_username: 
scholar_userid: 
orcid_id: 
medium_username: 
quora_username: 
publons_id: 
research_gate_profile: 
blogger_url: 
contact_note: 'Please drop me a line if you feel like.

'
google_analytics: UA-XXXXXXXXX
blog_name: Ars longa, vita brevis
blog_description: Notes on the History Ideas for the Complex Uncertain Future.
paginate: 4
permalink: "/blog/:year/:title/"
paginate_path: "/blog/page:num/"
text:
  pagination:
    newer: Newer
    older: Older
disqus_shortname: al-folio
show_social_icons: false
enable_anchorjs: false
enable_katex: true
news_limit: 5
markdown: kramdown
highlighter: pygments
include:
- _pages
exclude:
- vendor
plugins:
- jekyll-email-protect
- jekyll-paginate
- jekyll/scholar
- jemoji
scholar:
  last_name: Gomez-Ramirez
  style: apa
  locale: en
  sort_by: year
  order: descending
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
jquery_version: 1.12.4
katex_version: 0.9.0
anchorjs_version: 3.2.2
